### ISSUE TITLE
context.User.Identity.IsAuthenticated always false

### ISSUE THREAD

**Issue by tamil79** [alirizaadiyahsi/Kodkod#38]
Hi Sir,
     Authentication succeed and generated jwt token. when i call Users I am getting 401 unauthorized error. Please help me. I just downloaded your code and debugging in VS2017.
![login_success](https://user-images.githubusercontent.com/43854438/46482711-5a213800-c7b3-11e8-8ba0-add062b1cde5.png)
![context_user_isauthenticated_flase](https://user-images.githubusercontent.com/43854438/46482713-5a213800-c7b3-11e8-9c11-19a26eb59cb1.png)

Thanks
Tamil

**Comment by alirizaadiyahsi** [comment]
The user that you logged in should have admin access and userlist permissions. Did you check if user have these permissions?

**Comment by tamil79** [comment]
Yes Sir. I used login with admin/123qwe. 

FYI, I am using VS2017 and IIS Express to debug your project

**Comment by tamil79** [comment]
Hi Sir, I found the problem. Swashbuckle is not authorized properly

Thanks
Tamil
